// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSAD_Final_Project.Models;

#nullable disable

namespace WSAD_Final_Project.Migrations.Cars
{
    [DbContext(typeof(CarsContext))]
    [Migration("20231121140055_Cars")]
    partial class Cars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WSAD_Final_Project.Models.Cars", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int?>("BoughtYear")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CarMake")
                        .HasColumnType("int");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CarYear")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BoughtYear = 2016,
                            CarMake = 17,
                            CarModel = "Civic",
                            CarYear = 2005
                        },
                        new
                        {
                            CarId = 2,
                            BoughtYear = 2017,
                            CarMake = 17,
                            CarModel = "Civic",
                            CarYear = 2006
                        },
                        new
                        {
                            CarId = 3,
                            BoughtYear = 2018,
                            CarMake = 8,
                            CarModel = "CTS",
                            CarYear = 2008
                        },
                        new
                        {
                            CarId = 4,
                            BoughtYear = 2018,
                            CarMake = 46,
                            CarModel = "MR2",
                            CarYear = 1988
                        },
                        new
                        {
                            CarId = 5,
                            BoughtYear = 2019,
                            CarMake = 17,
                            CarModel = "Del Sol",
                            CarYear = 1994
                        },
                        new
                        {
                            CarId = 6,
                            BoughtYear = 2021,
                            CarMake = 14,
                            CarModel = "F150",
                            CarYear = 1999
                        },
                        new
                        {
                            CarId = 7,
                            BoughtYear = 2022,
                            CarMake = 14,
                            CarModel = "F250",
                            CarYear = 2001
                        },
                        new
                        {
                            CarId = 8,
                            BoughtYear = 2023,
                            CarMake = 31,
                            CarModel = "B2000",
                            CarYear = 1999
                        },
                        new
                        {
                            CarId = 9,
                            BoughtYear = 2022,
                            CarMake = 22,
                            CarModel = "Ninja",
                            CarYear = 2008
                        },
                        new
                        {
                            CarId = 10,
                            BoughtYear = 2022,
                            CarMake = 44,
                            CarModel = "GS750T",
                            CarYear = 1982
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
